### ISSUE TITLE
Tarea 2 HttpResponse

### ISSUE THREAD

**Issue by EstebanJCh97** [IC-6821/ic-6821-2020i-p1-viejostiempos#2]
La tarea busca implementar una clase HttpResponseImp, es la clase encargada de almacenar los datos que serán enviados al Browser Cliente por medio del Socket.

Su constructor debe recibir datos de tipo OutputStream para poder separarlos en sus respectivos campos.

HttpResponseImp debe tener su respectiva interfaz, HttpResponseImp debe tener un varios métodos, estructurados de la siguiente manera:

Metodos:

+ HttpResponseImp(OutputStream)
+ setVersion(String)
+ setStatusCode(int)
+ setStatusMessage(String)
+ appendHeader(String, String)
 + getData(OutputStream) 

Adjunto Imagen del Diseño UML de la Clase.
![imagen](https://user-images.githubusercontent.com/45090069/82894952-aa14bb80-9f10-11ea-952e-a721d5dc17df.png)

Adjunto  Link del DIseño UML del Proyecto.
https://app.diagrams.net/#G1mvgQr1nTqHRv2pAMCtDd_wM-LQ9YewB_

**Comment by christianacuna** [comment]
Ya fueron añadidos a master
