### ISSUE TITLE
Tarea 1 Log

### ISSUE THREAD

**Issue by Thelu04** [IC-6821/ic-6821-2020i-p1-viejostiempos#3]
Create  LogImp
La tarea busca implementar una clase LogImp debe ser Singleton. 
En primera instancia esta bitácora(Log) se enviará a la salida estándar (stdout). En el futuro se podrá configurar la salida a la que se enviará la bitácora.

LogImp debe tener su respectiva interfaz, LogImp debe tener uno o varios métodos.

Metodos:
+ createEntry(HttpRequest,HttpResponse) : Void

Adjunto Imagen del Diseño UML de la clase.
![imagen](https://user-images.githubusercontent.com/45090069/82988411-59f03480-9fb6-11ea-8898-015fde46ef27.png)

Adjunto Link del DIseño UML del proyecto.
https://app.diagrams.net/#G1mvgQr1nTqHRv2pAMCtDd_wM-LQ9YewB_

**Comment by christianacuna** [comment]
Ya fueron añadidos a master
